name: 

on:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: NPM clean install
              run: npm ci

            - name: npm run lint:fix
              run: npm run lint:fix

            - name: Commit linted files if any
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: 'Auto fix lint error(s)'

            # - name: Test
            #   run: npm run test

            - name: Clean and Build
              run: npm run clean && npm run build

            - name: Commit builded files if any
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: 'Auto build files'
